// Kalyan-Ji Bakery — Cake Creators Programme
// Shared data layer

const CAKE_DATA = {
  flavours: [
    { id: 'vanilla', name: 'Vanilla Bean', color: '#F5E6C8', description: 'Classic & creamy' },
    { id: 'chocolate', name: 'Dark Chocolate', color: '#3D1C02', description: 'Rich & indulgent' },
    { id: 'lemon', name: 'Lemon Zest', color: '#F5F0A0', description: 'Light & tangy' },
    { id: 'redvelvet', name: 'Red Velvet', color: '#8B1A1A', description: 'Velvety smooth' },
    { id: 'carrot', name: 'Carrot Spice', color: '#D4793B', description: 'Warm & spiced' },
    { id: 'pistachio', name: 'Pistachio', color: '#7DAA6F', description: 'Nutty & delicate' },
    { id: 'strawberry', name: 'Strawberry', color: '#E8697A', description: 'Fresh & fruity' },
    { id: 'marble', name: 'Marble', color: '#C8A882', description: 'Best of both worlds' },
  ],
  fillings: [
    { id: 'buttercream', name: 'Vanilla Buttercream', color: '#FFF8E7' },
    { id: 'choc-ganache', name: 'Chocolate Ganache', color: '#2C1206' },
    { id: 'lemon-curd', name: 'Lemon Curd', color: '#F7E87A' },
    { id: 'raspberry-jam', name: 'Raspberry Jam', color: '#C0394B' },
    { id: 'cream-cheese', name: 'Cream Cheese', color: '#FFFBE8' },
    { id: 'caramel', name: 'Salted Caramel', color: '#C68B3A' },
    { id: 'whipped-cream', name: 'Whipped Cream', color: '#FAFAFA' },
    { id: 'strawberry-compote', name: 'Strawberry Compote', color: '#D94F6A' },
  ],
  frostings: [
    { id: 'smooth-buttercream', name: 'Smooth Buttercream', style: 'smooth' },
    { id: 'rustic-swirl', name: 'Rustic Swirl', style: 'swirl' },
    { id: 'naked', name: 'Naked Cake', style: 'naked' },
    { id: 'drip', name: 'Drip Glaze', style: 'drip' },
    { id: 'textured', name: 'Textured Palette Knife', style: 'textured' },
    { id: 'fondant', name: 'Fondant Finish', style: 'fondant' },
  ],
  frostingColors: [
    { id: 'ivory', name: 'Ivory', hex: '#FFF8EE' },
    { id: 'blush', name: 'Blush Pink', hex: '#F2BEC5' },
    { id: 'champagne', name: 'Champagne', hex: '#E8C99A' },
    { id: 'sage', name: 'Sage Green', hex: '#A8C4A0' },
    { id: 'dusty-blue', name: 'Dusty Blue', hex: '#9BB4C8' },
    { id: 'lavender', name: 'Lavender', hex: '#C4A8D4' },
    { id: 'charcoal', name: 'Charcoal', hex: '#4A4A4A' },
    { id: 'chocolate-brown', name: 'Chocolate', hex: '#5C3317' },
    { id: 'coral', name: 'Coral', hex: '#E8806A' },
    { id: 'white', name: 'Pure White', hex: '#FFFFFF' },
  ],
  decorations: [
    { id: 'fresh-flowers', name: 'Fresh Flowers', emoji: '🌸' },
    { id: 'gold-leaf', name: 'Gold Leaf', emoji: '✨' },
    { id: 'sprinkles', name: 'Sprinkles', emoji: '🎊' },
    { id: 'macarons', name: 'Macarons', emoji: '🍪' },
    { id: 'berries', name: 'Fresh Berries', emoji: '🍓' },
    { id: 'chocolate-shards', name: 'Chocolate Shards', emoji: '🍫' },
    { id: 'sugar-pearls', name: 'Sugar Pearls', emoji: '⚪' },
    { id: 'edible-glitter', name: 'Edible Glitter', emoji: '💫' },
    { id: 'rosettes', name: 'Piped Rosettes', emoji: '🌹' },
    { id: 'fondant-shapes', name: 'Fondant Shapes', emoji: '⭐' },
  ],
  shapes: [
    { id: 'round', name: 'Round', icon: '⬤' },
    { id: 'square', name: 'Square', icon: '■' },
    { id: 'heart', name: 'Heart', icon: '♥' },
  ],
  sizes: [
    { id: 'small', name: 'Small', servings: '6–8', inches: '6"' },
    { id: 'medium', name: 'Medium', servings: '12–16', inches: '8"' },
    { id: 'large', name: 'Large', servings: '20–30', inches: '10"' },
    { id: 'tiered', name: 'Tiered', servings: '40–60', inches: '6"+10"' },
  ],
};

const TEMPLATE_CAKES = [
  {
    id: 'template-1',
    name: 'Garden Party',
    author: 'Kalyan-Ji Bakery',
    authorInitials: 'KJ',
    isTemplate: true,
    rating: 4.9,
    ratingCount: 128,
    likes: 342,
    comments: [],
    config: {
      flavour: 'vanilla',
      filling: 'lemon-curd',
      frosting: 'smooth-buttercream',
      frostingColor: 'blush',
      decorations: ['fresh-flowers', 'sugar-pearls'],
      shape: 'round',
      size: 'medium',
      tiers: 2,
      message: 'With Love',
      candles: true,
      candleCount: 0,
    },
    description: 'Delicate vanilla layers with lemon curd, blush buttercream and cascading fresh flowers.',
  },
  {
    id: 'template-2',
    name: 'Midnight Luxe',
    author: 'Kalyan-Ji Bakery',
    authorInitials: 'KJ',
    isTemplate: true,
    rating: 4.8,
    ratingCount: 96,
    likes: 287,
    comments: [],
    config: {
      flavour: 'chocolate',
      filling: 'choc-ganache',
      frosting: 'drip',
      frostingColor: 'charcoal',
      decorations: ['gold-leaf', 'chocolate-shards', 'edible-glitter'],
      shape: 'round',
      size: 'large',
      tiers: 3,
      message: '',
      candles: false,
      candleCount: 0,
    },
    description: 'Rich chocolate sponge, ganache filling, charcoal drip with gold leaf and chocolate shards.',
  },
  {
    id: 'template-3',
    name: 'Spring Blossom',
    author: 'Kalyan-Ji Bakery',
    authorInitials: 'KJ',
    isTemplate: true,
    rating: 4.7,
    ratingCount: 74,
    likes: 198,
    comments: [],
    config: {
      flavour: 'strawberry',
      filling: 'whipped-cream',
      frosting: 'naked',
      frostingColor: 'ivory',
      decorations: ['fresh-flowers', 'berries', 'edible-glitter'],
      shape: 'round',
      size: 'small',
      tiers: 1,
      message: 'Happy Birthday',
      candles: true,
      candleCount: 5,
    },
    description: 'Light strawberry sponge, whipped cream, naked finish adorned with spring florals and berries.',
  },
  {
    id: 'template-4',
    name: 'Golden Anniversary',
    author: 'Kalyan-Ji Bakery',
    authorInitials: 'KJ',
    isTemplate: true,
    rating: 5.0,
    ratingCount: 52,
    likes: 176,
    comments: [],
    config: {
      flavour: 'pistachio',
      filling: 'caramel',
      frosting: 'fondant',
      frostingColor: 'champagne',
      decorations: ['gold-leaf', 'sugar-pearls', 'rosettes'],
      shape: 'square',
      size: 'tiered',
      tiers: 4,
      message: '50 Years',
      candles: false,
      candleCount: 0,
    },
    description: 'Elegant pistachio layers with salted caramel, champagne fondant and gold leaf accents.',
  },
  {
    id: 'template-5',
    name: 'Red Velvet Dream',
    author: 'Priya S.',
    authorInitials: 'PS',
    isTemplate: false,
    rating: 4.6,
    ratingCount: 41,
    likes: 134,
    comments: [
      { author: 'Meera K.', text: 'This looks absolutely stunning!', time: '2 days ago' },
      { author: 'Raj T.', text: 'Ordered this for my mum\'s birthday — she loved it!', time: '1 week ago' },
    ],
    config: {
      flavour: 'redvelvet',
      filling: 'cream-cheese',
      frosting: 'rustic-swirl',
      frostingColor: 'white',
      decorations: ['rosettes', 'sugar-pearls'],
      shape: 'heart',
      size: 'medium',
      tiers: 2,
      message: 'Be Mine',
      candles: true,
      candleCount: 1,
    },
    description: 'Classic red velvet with cream cheese filling, rustic swirls and a heart shape — perfect for Valentine\'s.',
  },
  {
    id: 'template-6',
    name: 'Tropical Fiesta',
    author: 'Arjun M.',
    authorInitials: 'AM',
    isTemplate: false,
    rating: 4.5,
    ratingCount: 29,
    likes: 98,
    comments: [
      { author: 'Sunita B.', text: 'The colours are so vibrant and fun!', time: '3 days ago' },
    ],
    config: {
      flavour: 'lemon',
      filling: 'raspberry-jam',
      frosting: 'smooth-buttercream',
      frostingColor: 'coral',
      decorations: ['sprinkles', 'berries', 'macarons'],
      shape: 'round',
      size: 'medium',
      tiers: 2,
      message: 'Fiesta!',
      candles: true,
      candleCount: 21,
    },
    description: 'Bright lemon sponge with raspberry jam, coral buttercream, macarons and tropical sprinkles.',
  },
];

// Export to window so all scripts can access
window.CAKE_DATA = CAKE_DATA;
window.TEMPLATE_CAKES = TEMPLATE_CAKES;
